# Don't just call kubectl apply -f [file_name] on this file.  You need to set the enviroment variables, 
#     in base64 encoding and then call "$ envsubst < [file_name] | kubectl apply -f -"
apiVersion: v1
kind: Namespace
metadata:
  name: stone-data-lake

---
apiVersion: v1
kind: Secret
metadata:
  name: stone-data-lake-secret
  namespace: stone-data-lake
  labels:
    app: postgres
type: Opaque
data:
    postgres_root_username: ${postgres_root_username_b64}
    postgres_root_password: ${postgres_root_password_b64}
    pgadmin_root_username: ${pgadmin_root_username_b64}
    pgadmin_root_password: ${pgadmin_root_password_b64}
    keycloak_admin_username: ${keycloak_admin_username_b64}
    keycloak_admin_password: ${keycloak_admin_password_b64}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: stone-data-lake-configmap
  namespace: stone-data-lake
  labels:
    app: postgres
data:
  postgres-dbname: pg-data-lake
  postgres-db-location: ${postgres_local_path}