version: '3.3'

networks:
  data-lake:
    driver: bridge

#volumes:
#    prometheus_data: {}
#    grafana_data: {}

services:
## --------------------------------------------- NIFI SECTION ---------------------------------------------
  nifi:
    cap_add:
      - NET_ADMIN # low port bindings
    image: apache/nifi:1.25.0
    container_name: nifi
    ports:
      - "8080:8080/tcp" # HTTP interface
      - "8443:8443/tcp" # HTTPS interface
      - "514:514/tcp" # Syslog
      - "514:514/udp" # Syslog
      - "2055:2055/udp" # NetFlow
      - "3001:3001/udp" # dis_producer01
    environment:
      NIFI_WEB_HTTP_PORT: 8443
    networks:
      - data-lake
#    volumes:
#      - ./nifi/drivers:/opt/nifi/nifi-current/drivers
#      - ./nifi/certs:/opt/certs
#      - ./nifi/conf:/opt/nifi/nifi-current/conf
    restart: unless-stopped
#    links:
#      - dis_producer01
## ------------------------------------------- END NIFI SECTION -------------------------------------------



## ----------------------------------------------- PRODUCERS ----------------------------------------------
  dis_producer01:
    build: dis/.
    container_name: dis_producer01
    environment:
      SERVER: "nifi"
      SERVER_PORT: 3001
      SERVER_DELAY: 30
      SERVER_OPTION: 0
    networks:
      - data-lake
    restart: unless-stopped
    links:
      - nifi
  dis_producer02:
    build: dis/.
    container_name: dis_producer02
    environment:
      SERVER: "nifi"
      SERVER_PORT: 3002
      SERVER_DELAY: 10
      SERVER_OPTION: 1
    networks:
      - data-lake
    restart: unless-stopped
    links:
      - nifi
    