version: '3.3'

networks:
  data-lake:
    driver: bridge

volumes:
  shard01a_data: {}
  shard01a_config: {}


services:
## --------------------------------------- MONGO-EXPRESS (MONGO UI) ---------------------------------------
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin # MongoDB admin username
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin # MongoDB admin password
      ME_CONFIG_BASICAUTH_USERNAME: admin # Actual username
      ME_CONFIG_BASICAUTH_PASSWORD: admin # Actual password
      ME_CONFIG_MONGODB_SERVER: mongo_shard01a
      ME_CONFIG_MONGODB_PORT: "27122"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - data-lake
    links:
      - mongo_shard01a
## ------------------------------------- END MONGO-EXPRESS (MONGO UI) -------------------------------------

## ------------------------------------------------ MONGO -------------------------------------------------
  mongo_shard01a:
    build: mongo/shard/.
    container_name: mongo_shard01a
#    command: mongod --port 27017 --shardsvr --replSet shard01
#    security:
#      authorization: disabled
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27122:27017"
    networks:
      - data-lake
    volumes:
      - shard01a_data:/data/db
      - shard01a_config:/data/configdb
## ---------------------------------------------- END MONGO -----------------------------------------------

## --------------------------------------------- NIFI SECTION ---------------------------------------------
  nifi:
    cap_add:
      - NET_ADMIN # low port bindings
    image: apache/nifi:1.25.0
    container_name: nifi
    ports:
      - "8080:8080/tcp" # HTTP interface
      - "8443:8443/tcp" # HTTPS interface
      - "514:514/tcp" # Syslog
      - "514:514/udp" # Syslog
      - "2055:2055/udp" # NetFlow
      - "3001:3001/udp" # dis_producer01
    environment:
      NIFI_WEB_HTTP_PORT: 8443
    networks:
      - data-lake
    links:
      - mongo_shard01a
#    volumes:
#      - ./nifi/drivers:/opt/nifi/nifi-current/drivers
#      - ./nifi/certs:/opt/certs
#      - ./nifi/conf:/opt/nifi/nifi-current/conf
    restart: unless-stopped
#    links:
#      - dis_producer01
## ------------------------------------------- END NIFI SECTION -------------------------------------------



## ----------------------------------------------- PRODUCERS ----------------------------------------------
  dis_producer01:
    build: dis/.
    container_name: dis_producer01
    environment:
      SERVER: "nifi"
      SERVER_PORT: 3001
      SERVER_DELAY: 30
      SERVER_OPTION: 0
    networks:
      - data-lake
    restart: unless-stopped
    links:
      - nifi
  dis_producer02:
    build: dis/.
    container_name: dis_producer02
    environment:
      SERVER: "nifi"
      SERVER_PORT: 3002
      SERVER_DELAY: 10
      SERVER_OPTION: 1
    networks:
      - data-lake
    restart: unless-stopped
    links:
      - nifi
    