apiVersion: v1
kind: Namespace
metadata:
  name: data-lake
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: data-lake
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: data-lake
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: data-lake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password
            - name: POSTGRES_DB
              value: keycloak
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: data-lake
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: data-lake
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: data-lake
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: keycloak/keycloak:24.0.2
        args: ["start-dev"]
        ports:
        - containerPort: 8080
        env:
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KEYCLOAK_USER
          value: admin

        - name: DB_ADDR
          value: postgres
        - name: DB_DATABASE
          value: postgres
        - name: DB_PASSWORD
          value: admin
        - name: DB_USER
          value: admin
        - name: DB_VENDOR
          value: POSTGRES

# V3          
#        - name: KC_DB
#          value: postgres
#        - name: POSTGRES_DB
#          value: keycloak
#        - name: KC_DB_URL
#          value: jdbc:postgresql://postgres:5432/keycloak
#        - name: KC_DB_USERNAME
#          value: admin
#        - name: KC_DB_PASSWORD
#          value: admin

# V2
#        - name: KEYCLOAK_DB_URL
#          value: jdbc:postgresql://postgres:5432/postgres
#        - name: KEYCLOAK_DB_USER
#          value: admin
#        - name: KEYCLOAK_DB_PASSWORD
#          value: admin

# V1
#        - name: DB_VENDOR
#          value: postgres
#        - name: DB_ADDR
#          value: postgres
#        - name: DB_DATABASE
#          value: keycloak
#        - name: DB_USER
#          valueFrom:
#            secretKeyRef:
#              name: postgres-secret
#              key: username
#        - name: DB_PASSWORD
#          valueFrom:
#            secretKeyRef:
#              name: postgres-secret
#              key: password
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080