apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: stone-data-lake
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: stone-data-lake
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
#          image: quay.io/keycloak/keycloak:25.0.5
          image: localhost:5000/data-lake-keycloak
#          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: stone-data-lake-secret
                  key: keycloak_admin_username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stone-data-lake-secret
                  key: keycloak_admin_password
            - name: KC_PROXY
              value: "edge"
            - name: DB_VENDOR
              value: POSTGRES
            - name: DB_ADDR
              value: postgres-service
            - name: DB_DATABASE
              value: keycloak
            - name: DB_USER
              value: keycloak
            - name: DB_PASSWORD
              value: keycloak-password
#            - name: DB_VENDOR
#              value: postgres
#            - name: DB_HOST
#              value: postgres-service
#            - name: DB_PORT
#              value: "5432"
#            - name: DB_DATABASE
#              valueFrom:
#                secretKeyRef:
#                  name: stone-data-lake-secret
#                  key: keycloak_db
#              value: keycloak
#            - name: DB_USERNAME
#              valueFrom:
#                secretKeyRef:
#                  name: stone-data-lake-secret
#                  key: keycloak_db_username
#              value: keycloak
#            - name: DB_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: stone-data-lake-secret
#                  key: keycloak_db_password
#              value: keycloak
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080