#apiVersion: v1
#kind: Secret
#metadata:
#  name: pgadmin-secret
#type: Opaque
#data:
#  pgadmin-default-password: ${_password}
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: stone-data-lake
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4:8.11
          ports:
          - containerPort: 80
            name: pgadminport
#          env:
#           - name: PGADMIN_DEFAULT_EMAIL
#             value: "admin@admin.com"
#           - name: PGADMIN_DEFAULT_PASSWORD
#             valueFrom:
#               secretKeyRef:
#                 name: pgadmin-secret
#                 key: pgadmin-default-password
#           - name: PGADMIN_PORT
#             value: "80"
#          ports:
#            - containerPort: 80
#              name: pgadminport
          env:
          - name: PGADMIN_DEFAULT_EMAIL
            valueFrom:
              secretKeyRef:
                name: stone-data-lake-secret
                key: pgadmin_root_username
          - name: PGADMIN_DEFAULT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: stone-data-lake-secret
                key: pgadmin_root_password
          - name: PGADMIN_CONFIG_SERVER_MODE
            value: "True"
          volumeMounts:
          - name: pgadmin-data
            mountPath: /var/lib/pgadmin
      volumes:
      - name: pgadmin-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: stone-data-lake
  labels:
    app: pgadmin
spec:
  selector:
   app: pgadmin
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30200
    port: 80
#   - port: 80
#     nodePort: 30200