apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: stone-data-lake
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
#          image: dpage/pgadmin4:8.11
          image: localhost:5000/data-lake-pgadmin
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: stone-data-lake-secret
                  key: pgadmin_root_username
            - name: PGADMIN_DEFAULT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: stone-data-lake-secret
                  key: pgadmin_root_password
            - name: PGADMIN_CONFIG_SERVER_MODE
              value: "True"
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: stone-data-lake
  labels:
    app: pgadmin
spec:
  selector:
   app: pgadmin
  type: NodePort
  ports:
  - protocol: TCP
    nodePort: 30200
    port: 80
