apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-local-pvc
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
# Weirdly the storage for PVC must be less than the persistent-volumes size    
      storage: 5Gi
