apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-local-pv-01
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
#    path-for-windows: /run/desktop/mnt/host/c/PATH/TO/FILE
    path: /run/desktop/mnt/host/c/Users/c.stone/Documents/GitHub/data_lake_example/jupyter/work
#    path: /c/Users/c.stone/Documents/GitHub/data_lake_example/jupyter/work
#    path: /mnt/disks/ssd1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
#                - node-01
                