#ENTRYPOINT ["sh", "-c", "/superset-init.sh"]
#ENTRYPOINT ['/superset-init.sh']
#ENTRYPOINT [ "ls" ]

#FROM apache/superset

#RUN export SUPERSET_SECRET_KEY="1qaz@WSX!QAZ2wsx"
#RUN superset fab create-admin --username shoc --firstname SHOC --lastname H2O --email shoc@shoc.us --password JustKeepSwimming
#RUN superset fab create-admin --username shoc --firstname SHOC --lastname H2O --email shoc@shoc.us --password 34erdfcv%^TYGHBN
#RUN superset db upgrade
#RUN superset init

##RUN superset import-datasources -p /opt/superset/databases.yaml
##RUN superset import-dashboards -p dashboard_t_oil.zip -u shoc

