apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  labels:
    app: postgres
type: Opaque
data:
#    postgres-root-username: cm9vdA==
#    postgres-root-password: bXlwYXNzd29yZA==
    postgres-root-username: ${POSTGRES_USERNAME}
    postgres-root-password: ${POSTGRES_PASSWORD}