apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  labels:
    app: mongo
type: Opaque
data:
    mongo-root-username: ${POSTGRES_USERNAME}
    pmongo-root-password: ${POSTGRES_PASSWORD}